version: "3.7"

services:
  hello-world:
    hostname: hello-world
    container_name: hello-world
    # build:
    #   context: ./build
    #   dockerfile: Dockerfile
    image: jmaclean/hello-world:v3
    ports:
      - "80:80"
      - "443:443"
