version: "3.7"

services:
  micro-cheese:
    hostname: micro-cheese
    container_name: micro-cheese
    build:
      context: ./build
      dockerfile: Dockerfile
    image: jmaclean/micro-cheese:cheese
    ports:
      - "80:8080"
      - "443:8443"
    volumes: 
      - ./build/www:/app